using Pkg
Pkg.add("Random")
Pkg.add("CSV")
Pkg.add("DataFrames")
Pkg.add("DataTables")
Pkg.add("Distributions")
Pkg.add("PooledArrays")
Pkg.add("HTTP")
Pkg.add("XGBoost")
Pkg.add("DecisionTree")
Pkg.add("LightGBM")
Pkg.add("ROCAnalysis")
Pkg.add("BayesianOptimization")
Pkg.add("GaussianProcesses")
Pkg.add("Distributions")
Pkg.add("MLFlowLogger")
Pkg.add("MLFlowClient")
Pkg.add("DuckDB")
# Pkg.add("JuliaDB")